# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: pipeline-javascript

steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        npm install
        npm run build
        npm test
    displayName: 'npm install and build'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/' # App source code path relative to cwd
      api_location: '' # Api source code path relative to cwd
      output_location: '' # Built app content directory relative to app_location - optional
      cwd: '$(System.DefaultWorkingDirectory)' # Working directory - optional
      azure_static_web_apps_api_token: $(deployment_token)